name: "PR reviews"
description: "Outputs details about reviews on a PR"
author: "Walter Barros Galvao Neto"
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.  Defaults to github provided token.
    default: ${{ github.token }}
    required: false
  owner:
    description: The GitHub repo owner.  Defaults to github current repo owner.
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: The GitHub repo name.  Defaults to github current repo name.
    default: ${{ github.event.repository.name }}
    required: false
  pull_number:
    description: The GitHub pull request number.  Defaults to github current pull request number.
    default: ${{ github.event.pull_request.number }}
    required: false
  codeowners:
    description: A string containing the codeowner names
    required: true

outputs:
  approval_count:
    description: "Total amount of approvals"
  co_approval_count:
    description: "Total amount of code-owner approvals"
  non_co_approval_count:
    description: "Total amount of non-code-owner approvals"
runs:
  using: "node12"
  main: "dist/index.js"
